### ISSUE TITLE
org/slf4j/LoggerFactory

### ISSUE THREAD

**Issue by SrEnrique** [GeekyTheory/JGit-Example#1]
`Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at org.eclipse.jgit.lib.Repository.<clinit>(Repository.java:109)
    at org.eclipse.jgit.storage.file.FileRepositoryBuilder.build(FileRepositoryBuilder.java:92)
    at gitcontrol.GitControl.<init>(GitControl.java:47)
    at gitcontrol.Test.main(Test.java:17)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 4 more
Java Result: 1`

**Comment by ghost** [comment]
You need to add slf4j library to the project.
